// =================================================================
export const FETCH_RATE_NAMES_START = "APP/FETCH_RATE_NAMES_START";
export const FETCH_RATE_NAMES_SUCCESS = "APP/FETCH_RATE_NAMES_SUCCESS";
export const FETCH_RATE_NAMES_FAIL = "APP/FETCH_RATE_NAMES_FAIL";

export const SEARCH_CURRENT_MODAL = "MODAL/SEARCH_CURRENT_MODAL";

export const SWITCH_OBJECT_FROM = "FROM/SWITCH_OBJECT_FROM";

export const SET_CURRENT_OBJECT_FROM = "FROM/SET_CURRENT_OBJECT_FROM";
export const TOGGLE_FAVOURITE_MONETARY = "APP/TOGGLE_FAVOURITE_MONETARY";
export const SET_ORIGINAL_VALUE = "APP/SET_ORIGINAL_VALUE";

export const TOGGLE_CURRENT_MODAL = "APP/TOGGLE_CURRENT_MODAL";
export const TOGGLE_SETTING_MODAL = "APP/TOGGLE_SETTING_MODAL";
export const CLOSE_ALL_MODAL = "APP/CLOSE_ALL_MODAL";
