export const FECTH_RATES_START = "APP/FECTH_RATES_START";
export const FECTH_MONETARY_START = "APP/FETCH_MONETARY_START";
export const FETCH_RATES_FAILURE = "APP/FETCH_RATES_FAILURE";
export const FETCH_RATES_SUCCESS = "APP/FETCH_RATES_SUCCESS";

export const FETCH_MONETARY_FAILURE = "APP/FETCH_MONETARY_FAILURE";
export const FETCH_MONETARY_SUCCESS = "APP/FETCH_MONETARY_SUCCESS";

export const SET_ORIGINAL_VALUE = "APP/SET_ORIGINAL_VALUE";

export const TOGGLE_FAVOURITE_MONETARY = "APP/TOGGLE_FAVOURITE_MONETARY";

export const SET_ORGINAL_FORM = "APP/SET_ORGINAL_FORM";

// =================================================================
export const FETCH_RATE_NAMES_START = "APP/FETCH_RATE_NAMES_START";
export const FETCH_RATE_NAMES_SUCCESS = "APP/FETCH_RATE_NAMES_SUCCESS";
export const FETCH_RATE_NAMES_FAIL = "APP/FETCH_RATE_NAMES_FAIL";

export const SEARCH_CURRENT_MODAL = "MODAL/SEARCH_CURRENT_MODAL";

export const SWITCH_OBJECT_FROM = "FROM/SWITCH_OBJECT_FROM";

export const SET_CURRENT_OBJECT_FROM = "FROM/SET_CURRENT_OBJECT_FROM";
